name: Auto Create PR on Push

on:
  push:
    branches-ignore:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          gh pr create \
            --base master \
            --head ${{ github.ref_name }} \
            --title "Auto PR: ${{ github.ref_name }}" \
            --body "🚀 Automatically created PR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}